---
abstract: 'A collection of multiplex modules'
author:
  - 'Kan Liu <kan@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DynGig-Multiplex
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Errno: 0
  Fcntl: 0
  IO::Poll: 0.07
  IPC::Open3: 0
  POSIX: 0
  Socket: 0
  Test::More: 0
  Time::HiRes: 0
version: 1.03
