--- #YAML:1.0
name:               DynGig-Multiplex
version:            1.02
abstract:           A collection of multiplex modules
author:
    - Kan Liu <kan@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:         0
    Errno:        0
    Fcntl:        0
    IO::Poll:     0.07
    IPC::Open3:   0
    POSIX:        0
    Socket:       0
    Test::More:   0
    Time::HiRes:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
